# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: Docker@1
  displayName: 'Build an image'
  inputs:
    imageName: 'bestforyouregistry1.azurecr.io/repositoryname:$(Build.BuildId)'
- task: Docker@1
  displayName: Login
  inputs:
    azureSubscriptionEndpoint: 'ContosoAzureSubscription'
    azureContainerRegistry: bestforyouregistry1.azurecr.io
    command: login
- task: Docker@1
  displayName: 'Push an image'
  inputs:
    command: 'push'
    imageName: 'bestforyouregistry1.azurecr.io/$repositoryname:$(Build.BuildId)'
